### ISSUE TITLE
Als medewerker Sociale Zaken wil ik bij een bewoning het functieadres kunnen raadplegen (BewoningAPI)

### ISSUE THREAD

**Issue by kryban** [BRP-API/Haal-Centraal-BRP-bewoning#102]
...zodat ik per persoon kan bepalen of de persoon het adres als woonadres of briefadres gebruikt.

**Acceptatiecriteria**
- functieadres behoort niet tot adres, maar tot bewoner op het adres 
- meerder bewoners van een adres moeten moeten verschillende functieadressen (t.o.v. elkaar) moeten kunnen hebben over een gegeven tijd. 
- een bewoner moet in een periode slechts 1  functieadres hebben. Er mag geen overlap zijn in functieadressen van 1 persoon.

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Het kan niet voorkomen dat een adres zowel een brief- als een woonadres is.
Bij bewoning worden vanaf v2.0 alleen functieadres = woonadres opgenomen.

**Comment by CathyDingemanse** [comment]
functie-adres is niet langer onderdeel va de API

**Comment by CathyDingemanse** [comment]
functie adres wordt er uit gefilterd
