### ISSUE TITLE
Embedded personen in bewoning?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bewoning#107]
Nemen we de personen embedded op bij bewoningen? En is dat dan de hele persoon of de persoon beperkt?

overwegingen:
- opgeven gevraagde embedded velden is complex en veel (erger nog dan fields)
- grote berichten met veel herhaling

**Comment by fsamwel** [comment]
@CathyDingemanse hoe denk jij hierover? Moeten we wel direct de/alle persoonsgegevens kunnen krijgen van elke bewoner?

**Comment by CathyDingemanse** [comment]
Nee, volgens mij is dat niet nodig. Een link naar Personen en een identificatie is voldoende, aangazien de informatiebehoefte over bewoners en medebewoners zeer uiteenlopend is.

**Comment by CathyDingemanse** [comment]
Beste Mario, naam en geboortedatum van bewoners worden binnenkort meegegeven in Bewoning. Zie: [issue 240](https://github.com/orgs/BRP-API/projects/2?pane=issue&itemId=83783826&issue=BRP-API%7CHaal-Centraal-BRP-bewoning%7C240)
