### ISSUE TITLE
Moet een bewoning niet zelf ook een periode hebben?

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bewoning#108]
Een bewoning is een bepaalde samenstelling van bewoners, die elk zelf een periode hebben dat ze op het adres hebben gewoond. De gebruiker moet nu zelf afleiden uit al die begin- en einddatums van bewoners over welke periode deze bewoning gaat. Het zou makkelijker en duidelijker voor de gebruiker zijn wanneer we dat direct leveren

**Comment by fsamwel** [comment]
@CathyDingemanse mee eens?

**Comment by CathyDingemanse** [comment]
Ja helemaal mee eens.
