### ISSUE TITLE
Als PO wil ik dat de specificaties worden gecontroleerd op de levering van de verplichte gegevens 

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bewoning#122]
...zodat de Bewoning API specs kunnen worden uitgebreid met verplichte gegevens 
en compliant is aan de wet BRP

Het gaat om:
- in onderzoek
- indicatie geheim
- RNI
- opschorting

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
zo te zien zijn de specificaties helemaal in lijn met BRP Personen Bevragen voor wat betreft de verplicht te leveren gegevens (geheimhoudingPersoonsgegevens, rni, verificatie, opschortingBijhouding). Voor onderzoek is een iets afwijkende aanpak gekozen: indicatieVerblijfsplaatsInOnderzoek. Dat is denk ik een bewuste keuze om details te beperken waar die niet nodig zijn.

**Comment by fsamwel** [comment]
@CathyDingemanse kan ik dit issue nu sluiten?
