### ISSUE TITLE
Lijst van teleurstellingen

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bewoning#152]
##### Peildatum is 2010-08-19 maar verwachte periode is 2010-08-18 tot 2010-08-19. Dit hoort 2010-08-19 tot 2010-08-20 te zijn gezien eerdere scenarios.
- [x] Scenario: datum aanvang adreshouding van een persoon op het volgend adresseerbaar object is volledig onbekend en peildatum valt op de eerste dag na datum aanvang adreshouding op het eerste adresseerbaar object # features\raadpleeg-bewoning-op-peildatum\gba\overzicht-gba.feature:384

##### Instance toont haalcentraal/api/bewoning/bewoningen ipv eindigend op bewoning/bewoningen
- [x] Scenario: Gemeente raadpleegt bewoning van een adresseerbaar object buiten de gemeente # features\raadpleeg-bewoning-op-peildatum\gba\autorisatie-gba.feature:56
- [x] Scenario: Gemeente raadpleegt bewoning van een adresseerbaar object buiten de gemeente en de bewoner is nu wel ingeschreven in de gemeente # features\raadpleeg-bewoning-op-peildatum\gba\autorisatie-gba.feature:89

##### Protocollering feature bevat gemeente codes 0518 terwijl we 0800 hanteren vanwege tokens.
- [x] features\raadpleeg-bewoning-op-peildatum\gba\protocollering-gba.feature (Het probleem nu is dat de features wel slagen, maar bij debuggen zal geen afnemer zijn waar de gemeentecode 0518 is.)

##### Features missen achtergrond voor afnemer informatie en claim informatie. Nu falen alle scenarios omdat initieel nog niet werd gelet op het ad hoc medium.
- [x] features\raadpleeg-bewoning-op-peildatum\gba\geheimhouding-gba.feature
- [x] features\raadpleeg-bewoning-op-peildatum\gba\in-onderzoek-gba.feature
- [x] features\raadpleeg-bewoning-op-peildatum\gba\opschorting-bijhouding-gba.feature
- [x] features\raadpleeg-bewoning-op-peildatum\gba\overzicht-gba.feature

##### Overzicht-gba feature bevat nog niet geïmplementeerde step definition onderdelen. Specifiek 'En de 'verblijfplaats' is gewijzigd naar de volgende gegevens' levert de fout 'TypeError: Object.keys(...).findLast is not a function' in 'features\step_definitions\stepdefs.js:90:47'
- [x] features\raadpleeg-bewoning-op-peildatum\gba\overzicht-gba.feature:97
- [x] features\raadpleeg-bewoning-op-peildatum\gba\overzicht-gba.feature:98
- [x] features\raadpleeg-bewoning-op-peildatum\gba\overzicht-gba.feature:100

##### Fout-cases-gba.feature bevat een niet fout-case welke tevens verwarrend is
- [ ] Abstract Scenario: '\<accept media type\>' wordt opgegeven als Accept content type # features\fout-cases-gba.feature:83
    - Deze is apart aangezien er geen bewoningen worden verwacht, maar wat wordt hier nou precies getest? Het is geen fout case (waardoor deze verkeerd geplaatst is), maar als het geen fout case is, waarom hebben we 0 bewoningen? Ik verwacht op z'n minst een leeg bewoning response met peildatum en adresseerbaarObjectIdentificatie.
- [ ] Scenario: er is geen Accept header opgegeven # features\fout-cases-gba.feature:106
    - Deze is met name raar aangezien we niks verkeerds doen maar je verwacht 0 bewoningen terwijl je een peildatum met waarde 'gisteren' doet. Peildatum heeft waarde validatie en 'gisteren' zal incorrect zijn. Hier verwacht ik eerder een foutmelding.
- [ ] Scenario: er is een Accept header met lege waarde opgegeven # features\fout-cases-gba.feature:114
    - Zelfde vraagstuk als bij regel 106.
- [ ] Abstract Scenario: '\<media type\>' is opgegeven als Content-Type waarde # features\fout-cases-gba.feature:151
    - Zelfde vraagstuk als bij regel 106.
- [ ] Scenario: er is geen Content-Type header opgegeven # features\fout-cases-gba.feature:170
    - Zelfde vraagstuk als bij regel 106.
- [ ] Scenario: er is een Content-Type header met lege waarde opgegeven # features\fout-cases-gba.feature:178
    - Zelfde vraagstuk als bij regel 106.

##### Fout-cases-gba.feature heeft een 405 scenario die nieuw is voor GBA maar ook verkeerd lijkt te zijn geschreven
- [x] Abstract Scenario: bewoningen wordt gezocht met een '\<aanroep type\>' aanroep # features\fout-cases-gba.feature:190
    - Deze lijkt nog niet eerder te zijn genoemd als GBA feature. Is dat correct en zijn we die vergeten bij personen en reisdocumenten? Het is enkel bij de proxy genoemd.
    - Daarnaast is de tekst incorrect want dit is developer Engels en niet gebruiker Nederlands. De title 'Method not allowed. ' moet worden 'Gebruikte bevragingsmethode is niet toegestaan.' en de code 'methodNotAllowed' moet ook worden toegevoegd.

##### Peildatum heeft datum validatie
 - [ ] Het lijkt erop dat in de fout-cases-gba.features (root als raadpleeg bewoniner op peildatum) niet rekening houden met dat elke waarde dat niet een datum is, een foutmelding zal krijgen dat het geen geldige waarde is voor een datum. Er wordt alleen gecontroleerd of deze waarde niet gelijk staat tot NULL.

##### Veel bewoners heeft verwachting voor 1 bewoning, echter gezien de datum van en tot periode hoort dit twee bewoningen te zijn:
- [ ] Scenario: adresseerbaar object heeft in de gevraagde periode in totaal 100 bewoners en mogelijke bewoners # features\raadpleeg-bewoning-met-periode\gba\veel-bewoners-gba.feature:91
    - Er komen 2 bewoningen terug. 1 exact zoals gevraagd en een 2de waar de mogelijke bewoners niet meer mogelijk zijn want ze wonen er vanaf 20200800 en de datum van is 2020-08-18 en tot 2021-01-01. Zonder volgende datum of iets dergelijk is het logisch dat er 2 bewoningen worden geleverd voor deze periode.

##### Mogelijke-bewoners-gba.feature (peildatum en periode) hebben scenarios die niet overeenkomen met de rule waar deels onbekende vorige aanvang adreshouding worden verwacht, maar de scenarios bevatten 00000000
- [x] Scenario: onzekerheidsperiode van adreshouding overlapt onzekerheidsperiode van vorige adreshouding deels en peildatum ligt in de onzekerheidsperiode van de gevraagde adreshouding # features\raadpleeg-bewoning-op-peildatum\gba\mogelijke-bewoner-gba.feature:774
- [x] Scenario: onzekerheidsperiode van adreshouding overlapt onzekerheidsperiode van vorige adreshouding deels en peildatum ligt in de onzekerheidsperiode van de gevraagde adreshouding # features\raadpleeg-bewoning-op-peildatum\gba\mogelijke-bewoner-gba.feature:775
- [x] Scenario: onzekerheidsperiode van adreshouding overlapt onzekerheidsperiode van vorige adreshouding deels en peildatum ligt in de onzekerheidsperiode van de gevraagde adreshouding # features\raadpleeg-bewoning-met-periode\gba\mogelijke-bewoner-gba.feature:855
- [x] Scenario: onzekerheidsperiode van adreshouding overlapt onzekerheidsperiode van vorige adreshouding deels en peildatum ligt in de onzekerheidsperiode van de gevraagde adreshouding # features\raadpleeg-bewoning-met-periode\gba\mogelijke-bewoner-gba.feature:856
- [x] Scenario: onzekerheidsperiode van adreshouding overlapt onzekerheidsperiode van vorige adreshouding deels en peildatum ligt in de onzekerheidsperiode van de gevraagde adreshouding # features\raadpleeg-bewoning-met-periode\gba\mogelijke-bewoner-gba.feature:857

##### Scenarios bevatten datum regel brekende waarden.
 - [x] Scenario: persoon heeft onbekende aanvang adreshouding en deels/geheel overlappende onbekende aanvang volgende adreshouding en periode ligt tussen de eerste dag van de onzekerheidsperiode adreshouding en laatste dag van de onzekerheidsperiode volgende adreshouding # features\raadpleeg-bewoning-met-periode\gba\mogelijke-bewoner-gba.feature:525
    - datumVan is geen geldige waarde (april heeft geen 31 dagen).
 - [x] Scenario: datum aanvang vorige adreshouding ligt vóór onzekerheidsperiode van deels onbekende aanvang adreshouding en periode ligt vóór de onzekerheidsperiode van gevraagde adreshouding # features\raadpleeg-bewoning-met-periode\gba\mogelijke-bewoner-gba.feature:611
    - datumTot ligt voor datumVan.

**Comment by fsamwel** [comment]
@KayodeBakker misschien handig om te zeggen in welk bestand deze "teleurstelling" staat?

**Comment by MelvLee** [comment]
> En deze staat al checked. is die al opgelost?

ja, heb ik gefixed.

**Comment by KayodeBakker** [comment]
Bestand stond er ook Frank. features\raadpleeg-bewoning-op-peildatum\gba\overzicht-gba.feature:384 :)

**Comment by MelvLee** [comment]
> Abstract Scenario: '<accept media type>' wordt opgegeven als Accept content type # features\fout-cases-gba.feature:83

>    Deze is apart aangezien er geen bewoningen worden verwacht, maar wat wordt hier nou precies getest? Het is geen fout case (waardoor deze verkeerd geplaatst is), maar als het geen fout case is, waarom hebben we 0 bewoningen? Ik verwacht op z'n minst een leeg bewoning response met peildatum en adresseerbaarObjectIdentificatie.

Er wordt hier gevalideerd dat de 'accept media type' voorbeelden wordt geaccepteerd door de api.

de opgegeven adresseerbaar object bestaat niet in de scenario. Dan zou de bewoningen array leeg moeten zijn (0 bewoningen). Het zou volgens mij niet terecht zijn om een bewoning te retourneren zonder bewoon periodes. Er is dan geen onderscheid tussen het vragen van bewoning van een niet-bestaand adresseerbaar object en een bestaand adresseerbaar object die geen bewoners heeft op de aangegeven peildatum. Ik dacht dat ik hiervoor een scenario had gemaakt, maar die kan ik niet meer terugvinden.

**Comment by MelvLee** [comment]
> Abstract Scenario: bewoningen wordt gezocht met een '<aanroep type>' aanroep # features\fout-cases-gba.feature:190
Deze lijkt nog niet eerder te zijn genoemd als GBA feature. Is dat correct en zijn we die vergeten bij personen en reisdocumenten? Het is enkel bij de proxy genoemd.

Klopt. Ik zal het tzt ook toevoegen bij personen en reisdocumenten

**Comment by MelvLee** [comment]
> Daarnaast is de tekst incorrect want dit is developer Engels en niet gebruiker Nederlands. De title 'Method not allowed. ' moet worden 'Gebruikte bevragingsmethode is niet toegestaan.' en de code 'methodNotAllowed' moet ook worden toegevoegd.

Aangepast in commit: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/commit/3f0823aad587cf87da8e7f04cdc6be7e243d2d9a
