### ISSUE TITLE
Als PO wil ik een scenario voor autorisatie van gemeenten expliciet voor infrastructurele wijizgingen

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bewoning#158]
...zodat duidelijk is voor gebruikers welke gemeenten welke bewoningen mogen raadplegen.

**Acceptatiecriteria**
- [ ] bij gemeentelijke herindeling
- [ ] bij samenvoeging van gemeenten
- [ ] met tekening tijdslijnen

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Autorisatie van bewoning gebeurt door te kijken of het gevraagde adresseerbaar object binnen de gemeente ligt.

In de autorisatie feature hebben we hierbij nog geen rekening gehouden met gemeentelijke herindeling. Hetzelfde adresseerbare object kan op een moment binnen een gemeente liggen en een ander moment in een andere gemeente.

Als je dus in de database zoekt op adresseerbaar object identificatie kan je meerdere adressen vinden, waarvan sommige in de vragende gemeente liggen en sommige in een andere gemeente. Dit mag niet leiden tot een 403 not autorized fout wanneer de vraag gesteld wordt door de gemeente waarin het adresseerbaar object nu ligt.

Er zijn 2 soorten gemeentelijke herindeling:

1. samenvoegen van meerdere gemeenten in een nieuwe gemeente. Bijvoorbeeld o.a. Wateringen is overgegaan in gemeente Westland
2. overname van een deel van een gemeente door een andere gemeente. Bijvoorbeeld een deel van Rijswijk is overgegaan naar gemeente Den Haag (de wijk Ypenburg)

In het eerste geval moet de nieuwe gemeente (Westland) adresseerbare objecten kunnen bevragen van Wateringen, ook van vóór de gemeentelijke herindeling. Dit zou kunnen worden bepaald via de gemeententabel op basis van "Nieuwe code".

In het tweede geval is het niet nodig/toegestaan dat de nieuwe gemeente (Den Haag) deze objecten (in Ypenburg) kan raadplegen met een peildatum vóór de herindeling.
Dus wanneer Den Haag een adresseerbaar object in Ypenburg raadpleegt na de herindeling, moet hierop de bewoning worden geleverd. Wanneer Den Haag een adresseerbaar object in Ypenburg raadpleegt voor de herindeling, moet hierop een 403 worden gegeven. De vraag is of/hoe de API kan bepalen dat hier een 403 moet komen en geen 200 OK antwoord zonder bewoningen.

Complicatie hierbij is dat we testen met gemeente 0800. Dit is volgens de gemeentetabel precies een gemeente die is overgegaan in een andere gemeente (1728). Hiermee kan gemeentelijke herindeling dus niet goed getest worden. Ik kan dus geen scenario's schrijven die succesvol uitgevoerd kunnen worden.

**Comment by fsamwel** [comment]
@MelvLee @KayodeBakker hebben jullie een idee hoe we dit toch kunnen testen? Is het haalbaar om te vragen het testaccount in de IDP te wijzigen naar een andere gemeentecode? Dan moeten we dit aanpassen in features en automation van ook personen en reisdocumenten API.

**Comment by fsamwel** [comment]
oplossing is dat we in de Gegeven stap de gemeentetabel aanpassen
