### ISSUE TITLE
Scenario voor het wegfilteren van bewoningen waar geen functie adres bij aanwezig is

### ISSUE THREAD

**Issue by KayodeBakker** [BRP-API/Haal-Centraal-BRP-bewoning#225]
**Beschrijf de verbetering**
Op dit moment hebben we functionaliteit bedacht waar bewoningen met een briefadres als functie adres niet mogen worden getoond. Ook zijn er bewoningen welke geen functie adres hebben zoals buitenlandse adressen. Ook deze moeten worden weg gefilterd, maar dit laten we nog nergens zien in de scenarios.

**Comment by CathyDingemanse** [comment]
Dagstart donderdagochtend even bespreken.

**Comment by CathyDingemanse** [comment]
done
