### ISSUE TITLE
Als PO wil ik de URL van Bewoning veranderen van api/bewoning/bewoningen naar api/brp/bewoningen

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bewoning#230]
zodat Bewoning onderdeel wordt van het BRP API product
EN consistentie wordt bereikt in de URL van alle BRP API functies.

URL Personen: api/brp/personen
URL Verblijfplaatshistorie: api/brp/verblijfplaatshistorie

- [ ] OAS specificatie aanpassen
- [ ] overzicht maken URL omgevingen, beslissen of dit kan worden aangepast
- [ ] Plan voor migratie

**Comment by MelvLee** [comment]
@CathyDingemanse, reisdocumenten niet?

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse, reisdocumenten niet?

Ik vrees dat die API geen lang leven meer beschoren is. Het is de vraag of we daar moeite in moeten steken.
