### ISSUE TITLE
bewoning

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-bewoning#233]
release naar productie: 01-12-2024?
eerste release naar ACC: 14-10-2024?

- [x] #234
- [x] #235
- [x] #236
- [x] voorbeeld kubernetes manifests tbv deployment naar ACC. Zie: https://github.com/BRP-API/brp-shared-dotnet/tree/develop/.k8s/bewoningen

Container images:
- Autorisatie en Protocollering service: [1.5.0-202410170829](https://github.com/BRP-API/brp-shared-dotnet/pkgs/container/brp-autorisatie-protocollering/290608244?tag=1.5.0-202410170829)
- Bewoning Informatie service: [2.0.1-202410151130](https://github.com/BRP-API/bewoning-informatie-service/pkgs/container/bewoning-informatie-service/289365707?tag=2.0.1-202410151130)
- Bewoning Data service: [2.0.20-202410161341](https://github.com/BRP-API/bewoning-data-service/pkgs/container/bewoning-data-service/290125005?tag=2.0.20-202410161341)

**Comment by Patrick-4488** [comment]
overgebleven taken bij: https://github.com/orgs/BRP-API/projects/2/views/1?pane=issue&itemId=81898983
