### ISSUE TITLE
Als gebruiker van de bewoning API wil ik de naam en geboortedatum van bewoners zien

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bewoning#240]
...zodat ik weet wie de bewoners zijn zonder voor elke bewoner een raadpleeg-request te hoeven sturen.

Op verzoek van de gemeente Den Haag. Bij gebruik blijkt dat gebruikers van _alle bewoners_ meer gegevens moeten raadplegen, terwijl dat misschien niet nodig is. Met deze additionele gegevens kunnen zij een betere selectie maken van de personen waarvan andere gegevens moeten worden opgehaald.

Wens van:
Haagse Pandbrigade (huisvestingswet, overbewoning, illegale bewoning)
medewerkers WMO
Medewerkers domein inkomen (bijstand bijzondere bijstand)

**Acceptatiecriteria**
- [x] Bewoning levert naast burgerservicenummer ook de volledigNaam en geboortedatum (omdat je soms kind hebt die vernoemd is naar een ouder) van elke bewoner

**Definition of done**
- [x] features aangepast
- [x] [Open API specificatie: naam.volledigeNaam en geboorte.datum toegevoegd](https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/pull/251)
- [x] API's aangepast
- [x] Lokaal testen
- [x] In ACC testen
- [x] Vrijgaveadvies
- [x] Deployen naar proefomgeving
- [x] Deployen naar productie
- [x] Release notes aanpassen
- [x] Open API specificatie website
- [x] Releasenotes website

**Comment by CathyDingemanse** [comment]
In plaats van de geboortedatum graag de leeftijd leveren.

**Comment by nielskorporaal** [comment]
De Open API specificatie is te zien in Redoc.

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/BRP-API/bewoning-informatie-service/refs/heads/feature/%2320-leveren-leeftijd-en-volledige-naam-bewoner/specificatie/informatie-service/openapi.yaml

**Comment by CathyDingemanse** [comment]
Ik heb niet goed genoeg nagedacht over de leeftijd in het kader van bewoning. De actuele leeftijd tonen bij een historische bewoner is verwarrend. Een leeftijd geven voor de hele bewoningperiode is onmogelijk. Daarom is geboortejaar of geboortedatum toch beter. Graag even over hebben.

**Comment by fsamwel** [comment]
@nielskorporaal @MelvLee de versie van de OAS specificaties van de informatie-service is nog 2.0.0. Er zijn functionele wijzigingen aangebracht. Dan moet deze versie toch ook worden opgehoord naar 2.1.0?

**Comment by MelvLee** [comment]
> [@nielskorporaal](https://github.com/nielskorporaal) [@MelvLee](https://github.com/MelvLee) de versie van de OAS specificaties van de informatie-service is nog 2.0.0. Er zijn functionele wijzigingen aangebracht. Dan moet deze versie toch ook worden opgehoord naar 2.1.0?

@fsamwel, dat is nu gefixt. Zie #251
