### ISSUE TITLE
Als medewerker afvalplanning en containerbeheer wil ik weten hoeveel mensen wonen op een adres en wat hun leeftijd is

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-bewoning#47]
...zodat ik kan bepalen hoeveel (extra) containers de bewoners van een adres kunnen krijgen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Sinds 19 december 2019 is er wat veranderd in de specificaties. Leeftijd wordt niet meer opgenomen bij de bewoner. Aangezien de leeftijd wel bij de ingeschreven persoon wordt meegeleverd en deze embedded kan worden meegeleverd is deze functionele vraag ingevuld.

**Comment by CathyDingemanse** [comment]
Voor de story moet een oplossing worden gevonden o.b.v. dataminimalisatie. Toegang tot persoonsgegevens is niet nodig voor het aantal bewoners. Misschien ook nadenken over gebruik van statistische informatie over het aantal baby's (geboortes) in een wijk of buurt.
