### ISSUE TITLE
Nummeraanduiding als query-parameter ? 

### ISSUE THREAD

**Issue by JohanBoer** [BRP-API/Haal-Centraal-BRP-bewoning#92]
N.a.v.  PR #91 

@fsamwel fsamwel yesterday Member
@CathyDingemanse @MelvLee @JohanBoer waarom hebben we eigenlijk niet de zoekmogelijkheid op nummeraanduiding behouden en alleen zoeken op adoId toegevoegd?

Dit is in #8 besproken. Ik weet niet waarom we niet alsnog de nummeraanduidingIdentificatie als Query-parameter hebben toegevoegd, maar de wijzigingen als gevolg heb ik redelijk expliciet voorgesteld.
@fsamwel @CathyDingemanse : Gaan we hier nog een discussie over voeren ? Zo ja dan wacht ik met release 1.0.0.

**Comment by fsamwel** [comment]
ik heb er nog even over nagedacht, maar denk dat het beter is het nu zo te laten. Die parameter toevoegen kan altijd nog. 

Als we dat doen (nummeraanduiding parameter toevoegen) moeten we ook even nadenken over wat dat betekent: alle bewoning met die nummeraanduiding, of alle bewoning op het adresseerbaar object waarvan één van de adressen die nummeraanduiding heeft.
