### ISSUE TITLE
bij verloop datumVan en datumTotEnMet verplicht maken

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bewoning#97]
Op dit moment is in verloop geen enkele parameter verplicht. het is dus mogelijk verloop te vragen zonder periode. het is dan echter totaal onduidelijk over welke periode het verloop berekend is, waarschijnlijk sinds de start van de registratie dan wel sinds de bouw van het object tot vandaag.

Ik stel voor om datumVan en datumTotEnMet verplicht te maken in de API. 

N.B. dat zou een breaking change zijn

**Comment by CathyDingemanse** [comment]
ja, bij Den Haag
